### ISSUE TITLE
Deleting one character causes input to not work

### ISSUE THREAD

**Issue by johnny32** [retyui/react-native-confirmation-code-field#13]
This seems to only happen on iOS. Steps to reproduce:

1. Write the first character
2. Write the second character
3. Press backspace once to delete the second character
4. Write the second character again: the whole input gets deleted
5. Now everytime I reach the second character, it wipes all the characters

It looks like the "backspace" event is fired everytime I write something on the second input.

**Comment by retyui** [comment]
I try to reproduce in [Live Demo](https://snack.expo.io/@retyui/demo-for-react-native-confirmation-code-field) your steps, but all work.

Do you use latest version RN?

**Comment by johnny32** [comment]
I see it working there, but not on either the simulator or my iPhone X.

Here's the snippet code:

```
<CodeInput
    codeLength={4}
    inputPosition="center"
    variant="border-circle"
    autoFocus={true}
    onFulfill={this.handleOnSubmitEditing}
    containerProps={{ style: { marginBottom: 60 } }}
    style={{ zIndex: 2 }}
/>
```

**Comment by retyui** [comment]
What version react-native do you use ? And can make simple video demo?

**Comment by retyui** [comment]
@johnny32  ^^

**Comment by leonardobaggio** [comment]
The same issue has been discussed in the older repo and identified as a RN bug, that affect some older versions (the GIF demonstrates the exact behaviour @johnny32 wrote): 

https://github.com/ttdung11t2/react-native-confirmation-code-input/issues/14

Since this repo is proposed to be the active fork of the original 'react-native-confirmation-code-input', I would suggest [this PR](https://github.com/bkkwok/react-native-confirmation-code-input/commit/7ac9060c7f95f3830acddf8e13947ad075dd79a2) in order to fix this to users that are still using older versions of RN and due to dependency issues can not upgrade to the latest versions.

**Comment by retyui** [comment]
@leonardobaggio those PR already merged in the first version:
https://github.com/retyui/react-native-confirmation-code-field/blob/7f9aa00baa1f519fd75d90f880f6fbbc56d28948/src/components/ConfirmationCodeInput/ConfirmationCodeInput.js#L127-L152

```
yarn add react-native-confirmation-code-field@1
```
